/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas_rony;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class splasscren extends javax.swing.JFrame {

    /**
     * Creates new form splasscren
     */
    public splasscren() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        this.setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundpanel = new javax.swing.JPanel();
        loadingbar = new javax.swing.JProgressBar();
        loadinglabel = new javax.swing.JLabel();
        loadingvalue = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        backgroundpanel.setBackground(new java.awt.Color(51, 51, 51));
        backgroundpanel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        backgroundpanel.setPreferredSize(new java.awt.Dimension(1500, 900));
        backgroundpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadingbar.setBackground(new java.awt.Color(255, 255, 51));
        loadingbar.setForeground(new java.awt.Color(51, 255, 51));
        backgroundpanel.add(loadingbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 720, 1540, 30));

        loadinglabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        loadinglabel.setForeground(new java.awt.Color(255, 255, 255));
        loadinglabel.setText("Loading....");
        backgroundpanel.add(loadinglabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 690, 350, -1));

        loadingvalue.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        loadingvalue.setForeground(new java.awt.Color(255, 255, 255));
        loadingvalue.setText("0%");
        backgroundpanel.add(loadingvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 690, 60, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/Picture1.png"))); // NOI18N
        backgroundpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backgroundpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splasscren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splasscren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splasscren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splasscren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        splasscren sp = new splasscren();
        sp.setVisible(true);
        
        try{
            
            for(int i=0;i<=100;i++){
                    Thread.sleep(50);
            sp.loadingvalue.setText(i +"%");
            
            if(i==10){
                sp.loadinglabel.setText("Memulai Project...");
            }
            if(i==20){
                sp.loadinglabel.setText("Memuat Project...");
            }
            
            if(i==50){
                sp.loadinglabel.setText("Menghubungkan ke Program...");
            }
            if(i==70){
                sp.loadinglabel.setText("Berhasil Menghuubungkan ke Program....");
            }
            if(i==80){
                sp.loadinglabel.setText("Menjalankan Aplikasi...");
            }
            if(i==100){
                Login l =new Login();
                l.setVisible(true);
                sp.setVisible(false);
            }
            sp.loadingbar.setValue(i);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);      
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundpanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar loadingbar;
    private javax.swing.JLabel loadinglabel;
    private javax.swing.JLabel loadingvalue;
    // End of variables declaration//GEN-END:variables
}
